# version: '3.7'

# services:
#    web:
#        container_name: calculadora
#        build: ./
#        volumes:
#            - ./:/src
#        command: /src/install.sh
#        ports:
#            - 8020:8020
version: "3.1"

services:
    web:
        image: nginx:alpine
        container_name: calculadora_php_api
        working_dir: /app
        volumes:
            - ./:/app
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8020:80"
    php-fpm:
        build: .docker/php-fpm
        container_name: calculadora_php74
        working_dir: /app
        expose:
            - 9000
        volumes:
            - ./:/app
